### ISSUE TITLE
server booster doesn't work in 1.15.2 paper server

### ISSUE THREAD

**Issue by rakerall** [LoneDev6/ItemsAdder#131]
ERROR Error occurred while enabling ServerBooster v1.0.26 (Is it up to date?)
12.04 14:53:11 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/FieldUtils
12.04 14:53:11 [Server] INFO at dev.lone.serverbooster.b.a.a(SourceFile:131) ~[?:?]
12.04 14:53:11 [Server] INFO at dev.lone.serverbooster.b.a.d(SourceFile:120) ~[?:?]
12.04 14:53:11 [Server] INFO at dev.lone.serverbooster.b.a.e(SourceFile:141) ~[?:?]
12.04 14:53:11 [Server] INFO at dev.lone.serverbooster.Main.onEnable(SourceFile:86) ~[?:?]
12.04 14:53:11 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:291) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
12.04 14:53:11 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.reflect.FieldUtils
12.04 14:53:11 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202]
12.04 14:53:11 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
12.04 14:53:11 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
12.04 14:53:11 [Server] INFO ... 13 more
12.04 14:53:11 [Server] INFO Disabling ServerBooster v1.0.26
12.04 14:53:11 [Server] ERROR Error occurred while disabling ServerBooster v1.0.26 (Is it up to date?)
12.04 14:53:11 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
12.04 14:53:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:518) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:188) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[paper1.15.2.jar:git-Paper-66]
12.04 14:53:11 [Server] INFO at dev.lone.serverbooster.b.e.b.a.<init>(SourceFile:47) ~[?:?]

**Comment by LoneDev6** [comment]
Install https://www.spigotmc.org/resources/protocollib.1997/

thanks

**Comment by LoneDev6** [comment]
also remember this is for itemsadder not serverbooster reports
