### ISSUE TITLE
[BUG] Could not load the plugin

### ISSUE THREAD

**Issue by PeterMa9621** [LoneDev6/ItemsAdder#216]
**Describe the bug**
When I update ItemsAdder from 2.0.17 to 2.0.20, errors occur when I start my server. By looking at the error logs, I found that it appears because of the other plugin ArmorEquipEvent. When I remove that plugin, it works. But I need ArmorEquipEvent for other plugins.

**To Reproduce**
1. Put ArmorEquipEvent-1.7.12 into plugins folder.
2. Start the server
3. See error

**Expected behavior**
No error occurs.

**Error log**

> [19:57:18] [Server thread/WARN]: [ItemsAdder] Loaded class com.codingforcookies.armorequip.ArmorEquipEvent from ArmorEquipEvent v1.7.2 which is not a depend, softdepend or loadbefore of this plugin.
[19:57:18] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.0.20 (Is it up to date?)
java.lang.NoSuchMethodError: com.codingforcookies.armorequip.ArmorListener: method <init>()V not found
	at dev.lone.itemsadder.Main.onEnable(SourceFile:137) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[19:57:18] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.0.20
[19:57:18] [Server thread/ERROR]: Could not pass event PluginDisableEvent to ItemsAdder v2.0.20
java.lang.NullPointerException: null
	at dev.lone.itemsadder.h.c.b.ah(SourceFile:61) ~[?:?]
	at dev.lone.itemsadder.h.a.b(SourceFile:82) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-211]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:393) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: vanila 1.15.2
 - Plugin version: 2.0.20

**Comment by LoneDev6** [comment]
Thanks I will fix this error in next update (tomorrow)
